# Memento Python 초급 코스 Part 20 - 예외처리

**영상링크 : https://youtu.be/GRHcbM4gngM**

**CWK Memento Python : https://github.com/neobundy/CWK-Memento-Python - 소스코드**

## Intro

기쁜 소식이 있는데요. 오늘이 초급 딱지를 떼는 날입니다😁 

객체지향 프로그래밍을 다루진 않았지만 일반적인 생산성 향상이라면 procedural programming에 필요한 python 스킬은 오늘로 마무리가 된다고 할 수 있습니다. 초급은 오늘로 마무리를 하고 잠시 쉬었다가 객체지향 프로그래밍부터는 중급 수준의 눈높이에서 진행하려고 합니다. 

## 예외처리

초급 정리 마지막 시간인 오늘은 그간 미뤄왔던 예외 처리, Exception Handling을 다룹니다. 프로그래머라면 예상 가능한 모든 예외 상황에 대처할 수 있어야 하거든요. 지금까지도 예제 프로그램들 돌리면서 여러 차례 error 상황을 만났죠. 사실 지난 시간에 다룬 'file' 역시 수많은 예외 상황이 발생할 수 있습니다. 가장 흔한 게, 존재하지 않는 파일을 열라고 하는 건데 그런 간단한 예외 상황조차 처리하는 코드를 추가하지 않았죠. 존재하지 않는 파일을 열려고 하면 당연히 error가 납니다. 제대로 만든 프로그램이었다면 파일이 없다고 메시지를 출력하고 실행을 해야겠지만 그런 예외 상황에 대처하는 코드를 추가하지 않았기 때문에 프로그램이 비정상 종료되고 맙니다. 

예를 들어서 지금은 이게 처리를 한 거거든요. 아래 코드 참조

```python
    source = 'nosuchfile.cwk'

    try:
        lines = open(source, "rt")
    except FileNotFoundError:
        print(f'{source} not found. Want to create {source}?')
    except IOError:
        print('File I/O Error.')
    except:
        print('Unknown Error.')
    else:
        print(lines)
    finally:
        # TODO: save a temp file
        print('Temp file saved.')
```

가령 예외 처리를 하지 않고 이렇게 없는 파일을 열려고 하면 당연히 `file not found error` 예외가 발생합니다. 아래 코드 및 아웃풋 참조

```python
    source = 'nosuchfile.cwk'

    # try:
        lines = open(source, "rt")
    # except FileNotFoundError:
    #     print(f'{source} not found. Want to create {source}?')
    # except IOError:
    #     print('File I/O Error.')
    # except:
    #     print('Unknown Error.')
    # else:
    #     print(lines)
    # finally:
    #    # TODO: save a temp file
    #    print('Temp file saved.')
```

output:
```
Traceback (most recent call last):
  File "<stdin>", line 79, in <module>
    main()
  File "<stdin>", line 43, in <module> in main
    lines = open(source, "rt")
FileNotFoundError: [Errno 2] No such file or directory: 'nosuchfile.cwk'
```

비정상 종료되고는 프로그램은 예기치 못한 재앙을 불러올 수도 있는데요. 가령 실컷 몇 시간 작업을 하고 최종적으로 결과물을 저장하려고 하는데 파일 입출력 error가 발생을 하고 그런 예외 상황에 대처하는 코드를 마련해두지 않았다면 그 결과물 다 날리는 겁니다. 여기서도 지금 위와 같이 `file not found error` 예외 상황이 발생을 하죠. `open()` 함수로 열라고 한 source 파일이 존재하지 않기 때문입니다(`lines = open(source, "rt")`). 

error 메시지를 자세히 보면 `Traceback`이라고 하죠. error가 발생한 경로를 추적해줍니다. 근본적인 error는 `open()` 함수 call에서 발생을 했는데 이 함수를 호출한 건 또 `main()` 함수죠. 그리고 친절하게 행번호까지 알려줍니다. `79`, `43`.

`main()` 함수는 79였고 근본적으로 error가 발생한 `open()` call은 43이었다고. 그러면 43에 가보면 `lines = open(source, "rt")`에서 error가 난 거죠. 그럼 예외 상황에 대처하는 exception handling을 한번 해볼까요? 이렇게 처리를 해주면 깔끔하게 exception handling이 됩니다. 아래코드 참조

```python
    try:
        lines = open(source, "rt")
    except FileNotFoundError:
        print(f'{source} not found. Want to create {source}?')
    except IOError:
        print('File I/O Error.')
    except:
        print('Unknown Error.')
    else:
        print(lines)
    finally:
        # TODO: save a temp file
        print('Temp file saved.')
```

`try`, `except`, `except`, `except`, `else`, `finally` 여기서도 패턴인식 기술이 필요합니다. `try`, 해보라는 거죠. 해봤는데 예외가 발생을 했어요. `FileNotFoundError` 그러니까 파일이 존재하지 않는 예외가 발생을 하면 이 블럭을 실행을 하고. 아래코드 참조

```python
    except FileNotFoundError:
        print(f'{source} not found. Want to create {source}?')
```

파일 입출력 error가 발생을 하면 이 블럭을 실행을 하고. 아래코드 참조

```python
    except IOError:
        print('File I/O Error.')
```

여기에 앞에서 잡지 못한 다른 예외들은 except, default 값으로 처리를 하라는 뜻입니다.아래코드 참조

```python
    except:
        print('Unknown Error.')
```

예외가 발생하지 않으면 else 블럭을 실행을 합니다. 아래코드 참조

```python
    else:
        print(lines)
```

그리고 예외가 발생을 했든 정상적으로 실행이 됐든 무조건 finally 블럭이 실행됩니다. 아래코드 참조

```python
    finally:
        # TODO: save a temp file
        print('Temp file saved.')
```

그러니까 `try`, `except` 블럭에서 `try` 블럭에는 실행하고자 하는 코드를 입력을 하는 거고 `except`는 각각의 예외 상황에 대처하는 코드를 입력하는 겁니다. 

예외 처리하는 걸 흔히 exception 또는 'error를 캐치한다'고 하는데요. 

> Catch An Exception

전체적인 예외 처리는 exception handling이라고 합니다. except 블럭에 `file not found error`나 `IOerror`처럼 특정 type을 적어주면 그 예외만 잡습니다. 

그리고 이렇게 general하게 except라고만 써주면(`except :`) 그 예외만 잡습니다. default 값이에요. 나머지 모두 잡아줘요.

언뜻 통째로 잡아주니까 좋다고 생각할 수도 있지만 초간단 해법으로 보이죠. 구체적인 error 상황에 대처하기 어렵기 때문에 좋은 습관은 아닙니다. **이게 나중에는 고치기 힘든 습관이 돼요**. 가급적이면 위와 같이 구체적인 예외 상황에 대처하는 방식으로 작성하는게 낫습니다. 

except 블럭은 보다시피 중복될 수 있고요. 맨 마지막 except 블럭은 default 값이라고 했습니다. 그리고 이 `else` 블럭은 예외가 발생하지 않으면 실행되는 거고요. 

마지막에 나오는 `finally`는 정상 실행이 됐든 예외 상황이 발생을 했든 무조건 실행되는 블럭입니다. 여기서는 임시 파일의 작업 내용을 저장하는 루틴을 만든다고 가정을 하고 이 `TODO`를 만들어뒀죠. 아래 코드 참조

```python
    finally:
        # TODO: save a temp file
        print('Temp file saved.')
```

컴쟁이가 아니더라도 패턴 인식에 익숙한 호모사피엔스라면 `try` `except` `else` `finally` 정도는 이해하기 어렵지 않을 겁니다. 딱 봐도 한눈에 들어오잖아요. 마치 `if` 조건문 쭉 늘어놓는 거랑 비슷하죠. 

## 예외 상황 사례

이런 상황이 발생할 수도 있어요. 지난 시간에 저장했던 일본어 dictionary pickle data base 있잖아요. 여기서 단어를 하나를 출력하려고 하는데 dictionary에 존재하지 않는 단어라면 또 error가 날 겁니다. 그럼 `FileNotFound` 예외처럼 key error exception을 잡아주면 되거든요. 이걸 캐치해주면 되는데 또 없는 단어를 한 번 사전에서 찾아보겠습니다. 아래코드 참조

```python
    source = 'japanese_dictionary.cwkdb'
    dic = read_database(source)

    # word = 'もらう[貰う]'
    word = 'もらう'
    # try:
    print(dic[word])
    # except KeyError:
    #    print(f'Word not found: {word}.')
```

그럼 당연히 key error가 나죠. `KeyError: 'もらう'`. 아래 아웃풋 참조

output:
```
Traceback (most recent call last):
  File "<stdin>", line 79, in <module>
    main()
  File "<stdin>", line 64, in main
    print(dic[word])
KeyError: 'もらう'
```

왜냐하면 もらう하고 한자까지 포함해서 key로 사용을 하고 있기 때문에 이 단어는 없다고 지금 key error가 나는 거죠. dictionary에 그런 key는 없다고. 이렇게 해야 제대로 나옵니다. 아래코드 참조

```python
    source = 'japanese_dictionary.cwkdb'
    dic = read_database(source)

    word = 'もらう[貰う]'
    # word = 'もらう'
    # try:
    print(dic[word])
    # except KeyError:
    #    print(f'Word not found: {word}.')
```

`받다` `얻다` `인수하다` `맡다` 뭐 이렇게. 아래 아웃풋 참조

output:
```
받다, 얻다, 인수하다, 맡다
```

그러니까 dictionary에서 원하는 단어를 찾으려고 하는데 그런 key가 없으면 exception이 발생하겠죠. key error가 발생을 합니다. key error가 발생을 하면 그런 단어가 발견되지 않았다고 출력을 하고 정상적으로 프로그램을 계속 실행하는 겁니다. 

뭐 여기서는 달랑 `error` 메시지만 출력을 하지만 '그런 단어 없는데 새로 입력하시겠습니까?' 그런 루틴을 추가할 수도 있겠죠. 그럼 더 근사해지겠죠. 

예외는 일부러 만들어낼 수도 있습니다. 가령 숫자만 입력을 해야 되는데 사용자가 문자를 입력하면 type error 같은 예외 상황을 만들 수 있는데요. 지금 여기 `get_number()`라는 함수가 정의되어 있는데 한 번 볼까요? 아래코드 참조

```python
def get_number():

    number = input("Enter a number: ")
    if not number.isnumeric():
        raise TypeError(f'What are you, stupid? \'{number}\' is not a number.')
    else:
        return number
```

`get_number()`를 보면 사용자가 입력한 값이 숫자가 아니면(`if not number.isnumeric():`) 뭐라고 투덜대죠? 정상적으로 그 숫자가 입력됐으면 그 숫자를 돌려줍니다(`retrun number`).

여기서 `raise TypeError`잖아요. `type error`라는 예외 상황을 일부러 만들어내는 겁니다. 그럴 때 `raise` Statement을 사용합니다. 

그러면 `get_number()`를 호출한 `main()` 함수에서 타입 error exception을 잡아서 캐치해서 그에 맞는 처리를 해주면 되겠죠. 아래코드 참조

```python
    try:
        number = get_number()
    except TypeError as e:
        print(f'Error occurred: {e}')
    else:
        print(f'{number} accepted.')
```

`as` 키워드를 사용을 해서 별칭을 줄 수도 있습니다. 그리고 문자열에서 출력할 수도 있죠. 해볼까요? 숫자를 입력하면 정상적으로 실행이 됩니다. 아래 아웃풋 참조

output:
```
Enter a number: 123
123 accepted.
```

엉뚱한 값을 입력하면 너 뭐하냐고 욕을 하죠. 아래 아웃풋 참조

output:
```
Enter a number: qwer
Error occurred: What are you, stupid? 'qwer' is not a number.
```

사실 두고두고 쓸 범용 프로그램이 아니라면 간단한 작업에 필요한 거의 몇 번 쓰고 버릴 그런 coding script라면 컴쟁이들도 굳이 예외 처리를 하지 않습니다. 저도 마찬가지인데요. 시간 낭비일 수도 있으니까요. 그런데 두고두고 쓸 스크립트 이상의 프로그래밍이라면 예외 처리는 필수입니다. 특히 파일 입출력처럼 결과물을 날릴 수도 있는 critical한 작업이라면 두말할 나위가 없겠죠.

오늘은 간단히 예외 처리를 정리해봤습니다. 클래스 그러니까 객체지향 프로그래밍만 제외하면 웬만한 Python 프로그래밍 책에서 다루는 내용은 대강이라도 모두 정리했다고 할 수 있습니다. 실생활에서 자꾸 응용을 하면서 짬밥을 늘려가 보세요. 객체지향 프로그래밍까지 가지 않더라도 지금까지 배운 내용만으로도 삽질을 되풀이하면서 컴퓨터의 노예로 사는 일은 거의 사라질 겁니다.

초보 연재 마쳤으니까 잠깐 쉬겠습니다. 중급 연재의 큰 줄기는 Python 객체지향 프로그래밍일 겁니다. 그 객체지향 프로그래밍 연재에서 다시 뵙겠습니다. 

노파심에서 마지막으로 다시 잔소리하지만 **눈으로만 봐온 분이 있다면 맨날 제자리 걸음일 겁니다**. 코딩은 보는 거랑 직접 해보는 거랑 하늘과 땅 차이예요. 해보면 압니다. **뜻대로 되는 게 하나도 없으니까**. ***여러분의 맨땅의 헤딩 여정에 건투를 빕니다***.